language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.4.5
  - DJANGO=django==1.5

install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install Pillow --use-mirrors"
  - "touch bluebottle/settings/local.py"
  - "touch bluebottle/settings/secrets.py"

matrix:
  allow_failures:
    - env: DJANGO=django==1.5

script:
  - python ./manage.py test --settings=bluebottle.settings.travis -v 2
